FROM elixir:1.8.1-alpine as builder

ENV MIX_ENV test

RUN apk add --no-cache bash git build-base

RUN mix local.hex --force
RUN mix local.rebar --force

WORKDIR /app
COPY . /app

RUN mix format --check-formatted
RUN mix deps.get
RUN mix deps.compile

CMD mix test --trace