version: "3.4"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    build:
      context: .
      dockerfile: Dockerfile-test

    extra_hosts:
     - "kafka:127.0.0.1"

    # depends_on:
    #   - zookeeper
    #   - kafka

    # command: sh -c "mix test --trace"
    command: sh -c "bash"
